#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo ""
echo "提交格式不符合规范，请使用以下格式："
echo "请使用以下格式提交: <type>(<scope>): <subject>"
echo "示例:"
echo "feat(用户管理): 添加登录功能"
echo 'feat',//新特性、新功能
echo 'fix',//修改bug
echo 'docs',//文档修改
echo 'style',//代码格式修改, 注意不是 css 修改
echo 'refactor',//代码重构
echo 'perf',//优化相关，比如提升性能、体验
echo 'test',//测试用例修改
echo 'chore',//其他修改, 比如改变构建流程、或者增加依赖库、工具等
echo 'revert',//回滚到上一个版本
echo 'build',//编译相关的修改，例如发布版本、对项目构建或者依赖的改动
echo "注意:"
echo "  1. 冒号后必须有一个空格"
echo "  2. 描述使用中文，首字母小写，结尾不要加句号"
echo "详细规范请参考：https://www.conventionalcommits.org/zh-hans/v1.0.0/"
pnpm exec commitlint --edit "$1" --config commitlint.config.cjs

